export const SKILL_IR = [
    'کهکشانی ',
    'آرمانی ',
    'جادویی ',
    'افسانه ای ',
    'خارق العاده ',
    'استثنایی ',
    'فوق العاده ',
    'بین المللی ',
    'باشکوه ',
    'درخشان ',
    'برجسته ',
    'توانمند ',
    'عالی ',
    'خوب ',
    'قابل قبول ',
    'ناکافى ',
    'ضعیف ',
    'ناچیز ',
    'اسفبار ',
    'افتضاح ',
    'بدون مهارت '
];

export const SKILL_ENG = [
    'divine very high',
    'divine high',
    'divine low',
    'divine very low',
    'utopian very high',
    'utopian high',
    'utopian low',
    'utopian very low',
    'magical very high',
    'magical high',
    'magical low',
    'magical very low',
    'mythical very high',
    'mythical high',
    'mythical low',
    'mythical very low',
    'extra-terrestrial very high',
    'extra-terrestrial high',
    'extra-terrestrial low',
    'extra-terrestrial very low',
    'titanic very high',
    'titanic high',
    'titanic low',
    'titanic very low',
    'supernatural very high',
    'supernatural high',
    'supernatural low',
    'supernatural very low',
    'worldclass very high',
    'worldclass high',
    'worldclass low',
    'worldclass very low',
    'magnificent very high',
    'magnificent high',
    'magnificent low',
    'magnificent very low',
    'brilliant very high',
    'brilliant high',
    'brilliant low',
    'brilliant very low',
    'outstanding very high',
    'outstanding high',
    'outstanding low',
    'outstanding very low',
    'formidable very high',
    'formidable high',
    'formidable low',
    'formidable very low',
    'excellent very high',
    'excellent high',
    'excellent low',
    'excellent very low',
    'solid very high',
    'solid high',
    'solid low',
    'solid very low',
    'passable very high',
    'passable high',
    'passable low',
    'passable very low',
    'inadequate very high',
    'inadequate high',
    'inadequate low',
    'inadequate very low',
    'weak very high',
    'weak high',
    'weak low',
    'weak very low',
    'poor very high',
    'poor high',
    'poor low',
    'poor very low',
    'wretched very high',
    'wretched high',
    'wretched low',
    'wretched very low',
    'disastrous very high',
    'disastrous high',
    'disastrous low',
    'disastrous very low'
];

export const SKILL_NUMBER = [
    20.75, 20.5, 20.25, 20,
    19.75, 19.5, 19.25, 19,
    18.75, 18.5, 18.25, 18,
    17.75, 17.5, 17.25, 17,
    16.75, 16.5, 16.25, 16,
    15.75, 15.5, 15.25, 15,
    14.75, 14.5, 14.25, 14,
    13.75, 13.5, 13.25, 13,
    12.75, 12.5, 12.25, 12,
    11.75, 11.5, 11.25, 11,
    10.75, 10.5, 10.25, 10,
    9.75, 9.5, 9.25, 9,
    8.75, 8.5, 8.25, 8,
    7.75, 7.5, 7.25, 7,
    6.75, 6.5, 6.25, 6,
    5.75, 5.5, 5.25, 5,
    4.75, 4.5, 4.25, 4,
    3.75, 3.5, 3.25, 3,
    2.75, 2.5, 2.25, 2,
    1.75, 1.5, 1.25, 1

];

export const TEAM_SPIRITS = [
    // 'No Action',
    // 'like the Cold War',
    'murderous (1)',
    'furious (2)',
    'irritated (3)',
    'composed (4)',
    'calm (5)',
    'content (6)',
    'satisfied (7)',
    'delirious (8)',
    'walking on clouds (9)',
    'Paradise on Earth! (10)'
];
